[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "server"
path = "cmd/main.rs"

[lib]
name = "server_lib"
path = "src/lib.rs"

[dependencies]
tokio = { version = "^1.14.0", features = ["macros", "rt"] }
tokio-udev = "^0.7.0"
futures-util = "^0.3.18"

