[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "server"
path = "cmd/main.rs"

[lib]
name = "server_lib"
path = "src/lib.rs"

[dependencies]
tokio = { version = "^1.14.0", features = ["macros", "rt", "sync", "net"] }
#udev = { version = "^0.6.2", features = ["mio"] }
udev = { git = "https://github.com/d0u9/udev-rs", branch = "send" }
libc = "0.2"
mio = { version = "^0.7", features = ["os-ext"] }
